Dockerize spooder OSC web application
on: release
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ sectets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/main
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: {{ secrets.DOCKER_USERNAME }}
          password: {{ secrets.DOCKER_PASSWORD }}
          repository: valnar012/spooder
          tags: latest, ${{ github.run_number }}
