version: '2'

networks:
  app:

services:
  app:
    build:
      context: docker/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app
    volumes:
      - ./:/app:delegated
  ngrock:
    image: ngrok/ngrok:latest
    ports:
      - "4040:4040"
    environment:
      NGROK_AUTH: ${NGROK_AUTH}
      NGROK_REGION: us
      NGROK_PROTOCOL: http
      NGROK_PORT: "80"
    networks:
      - app
