version: '2'

networks:
  app:

services:
  app:
    build:
      context: docker/
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app
    volumes:
      - ./:/app:delegated
